export type Caricature = {
  id: string;
  label: string;
  emoji: string;
  photo?: string;
  /** Full 52-blendshape map captured from the reference photo via /extract. */
  extracted?: Record<string, number>;
  /** Subset of blendshape names that count toward the match score. */
  activeKeys?: string[];
  /** Hand-tuned values that win over `extracted` for the given key. */
  overrides?: Record<string, number>;
  /** Resolved scoring target. Computed from extracted+activeKeys+overrides if absent. */
  target: Record<string, number>;
  weights?: Record<string, number>;
  threshold?: number;
  /** Soft cap per face in ms; default 20000. On expiry, advance with a miss. */
  capMs?: number;
};

type RawCaricature = Omit<Caricature, 'target'> & { target?: Record<string, number> };

function resolveTarget(c: RawCaricature): Record<string, number> {
  if (c.target) return c.target;
  if (!c.extracted || !c.activeKeys) {
    throw new Error(
      `Caricature ${c.id} needs either target or (extracted + activeKeys)`,
    );
  }
  const out: Record<string, number> = {};
  for (const k of c.activeKeys) {
    const v = c.overrides?.[k] ?? c.extracted[k];
    if (v != null) out[k] = v;
  }
  return out;
}

function resolve(list: RawCaricature[]): Caricature[] {
  return list.map((c) => ({ ...c, target: resolveTarget(c) }));
}

export const PLACEHOLDER_CARICATURES: Caricature[] = resolve([
  {
    id: 'frame1',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame1.jpg',
    activeKeys: ["mouthLowerDownRight","mouthLowerDownLeft","browOuterUpLeft","browInnerUp","browOuterUpRight"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0,
      "browInnerUp": 0.641,
      "browOuterUpLeft": 0.73,
      "browOuterUpRight": 0.577,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.022,
      "eyeBlinkRight": 0.013,
      "eyeLookDownLeft": 0.047,
      "eyeLookDownRight": 0.048,
      "eyeLookInLeft": 0.164,
      "eyeLookInRight": 0.066,
      "eyeLookOutLeft": 0.025,
      "eyeLookOutRight": 0.074,
      "eyeLookUpLeft": 0.283,
      "eyeLookUpRight": 0.254,
      "eyeSquintLeft": 0.392,
      "eyeSquintRight": 0.252,
      "eyeWideLeft": 0.056,
      "eyeWideRight": 0.069,
      "jawForward": 0.001,
      "jawLeft": 0,
      "jawOpen": 0.568,
      "jawRight": 0.244,
      "mouthClose": 0.002,
      "mouthDimpleLeft": 0.066,
      "mouthDimpleRight": 0.075,
      "mouthFrownLeft": 0.001,
      "mouthFrownRight": 0.001,
      "mouthFunnel": 0.009,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.735,
      "mouthLowerDownRight": 0.747,
      "mouthPressLeft": 0.005,
      "mouthPressRight": 0.011,
      "mouthPucker": 0.043,
      "mouthRight": 0.007,
      "mouthRollLower": 0.004,
      "mouthRollUpper": 0.018,
      "mouthShrugLower": 0.001,
      "mouthShrugUpper": 0.004,
      "mouthSmileLeft": 0,
      "mouthSmileRight": 0.001,
      "mouthStretchLeft": 0,
      "mouthStretchRight": 0.005,
      "mouthUpperUpLeft": 0.002,
      "mouthUpperUpRight": 0.001,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame4',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame4.jpg',
    activeKeys: ["eyeSquintRight","mouthLowerDownRight","eyeLookDownRight","eyeLookDownLeft","mouthUpperUpRight"],
    extracted: {
      "browDownLeft": 0.002,
      "browDownRight": 0.001,
      "browInnerUp": 0.309,
      "browOuterUpLeft": 0.37,
      "browOuterUpRight": 0.228,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.109,
      "eyeBlinkRight": 0.1,
      "eyeLookDownLeft": 0.406,
      "eyeLookDownRight": 0.409,
      "eyeLookInLeft": 0.036,
      "eyeLookInRight": 0.196,
      "eyeLookOutLeft": 0.185,
      "eyeLookOutRight": 0.017,
      "eyeLookUpLeft": 0.034,
      "eyeLookUpRight": 0.032,
      "eyeSquintLeft": 0.385,
      "eyeSquintRight": 0.555,
      "eyeWideLeft": 0.012,
      "eyeWideRight": 0.014,
      "jawForward": 0.001,
      "jawLeft": 0.012,
      "jawOpen": 0.205,
      "jawRight": 0,
      "mouthClose": 0.001,
      "mouthDimpleLeft": 0.013,
      "mouthDimpleRight": 0.022,
      "mouthFrownLeft": 0,
      "mouthFrownRight": 0,
      "mouthFunnel": 0.135,
      "mouthLeft": 0.001,
      "mouthLowerDownLeft": 0.371,
      "mouthLowerDownRight": 0.43,
      "mouthPressLeft": 0.005,
      "mouthPressRight": 0.019,
      "mouthPucker": 0.026,
      "mouthRight": 0,
      "mouthRollLower": 0.004,
      "mouthRollUpper": 0.002,
      "mouthShrugLower": 0.001,
      "mouthShrugUpper": 0.029,
      "mouthSmileLeft": 0.02,
      "mouthSmileRight": 0.021,
      "mouthStretchLeft": 0.002,
      "mouthStretchRight": 0.002,
      "mouthUpperUpLeft": 0.361,
      "mouthUpperUpRight": 0.4,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame5',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame5.jpg',
    activeKeys: ["browOuterUpLeft","mouthLowerDownLeft","mouthLowerDownRight","browInnerUp","mouthUpperUpRight"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0.001,
      "browInnerUp": 0.512,
      "browOuterUpLeft": 0.857,
      "browOuterUpRight": 0.143,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.006,
      "eyeBlinkRight": 0.007,
      "eyeLookDownLeft": 0.189,
      "eyeLookDownRight": 0.198,
      "eyeLookInLeft": 0.116,
      "eyeLookInRight": 0.113,
      "eyeLookOutLeft": 0.06,
      "eyeLookOutRight": 0.049,
      "eyeLookUpLeft": 0.08,
      "eyeLookUpRight": 0.071,
      "eyeSquintLeft": 0.035,
      "eyeSquintRight": 0.041,
      "eyeWideLeft": 0.162,
      "eyeWideRight": 0.134,
      "jawForward": 0.006,
      "jawLeft": 0.017,
      "jawOpen": 0.209,
      "jawRight": 0,
      "mouthClose": 0,
      "mouthDimpleLeft": 0.002,
      "mouthDimpleRight": 0.018,
      "mouthFrownLeft": 0.001,
      "mouthFrownRight": 0.001,
      "mouthFunnel": 0.078,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.791,
      "mouthLowerDownRight": 0.756,
      "mouthPressLeft": 0.001,
      "mouthPressRight": 0.017,
      "mouthPucker": 0.011,
      "mouthRight": 0.003,
      "mouthRollLower": 0.001,
      "mouthRollUpper": 0.006,
      "mouthShrugLower": 0,
      "mouthShrugUpper": 0.007,
      "mouthSmileLeft": 0.082,
      "mouthSmileRight": 0.221,
      "mouthStretchLeft": 0.012,
      "mouthStretchRight": 0.106,
      "mouthUpperUpLeft": 0.103,
      "mouthUpperUpRight": 0.332,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame6',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame6.jpg',
    activeKeys: ["browInnerUp","browOuterUpLeft","browOuterUpRight","mouthLowerDownRight","mouthLowerDownLeft"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0,
      "browInnerUp": 0.798,
      "browOuterUpLeft": 0.773,
      "browOuterUpRight": 0.739,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.003,
      "eyeBlinkRight": 0.001,
      "eyeLookDownLeft": 0.247,
      "eyeLookDownRight": 0.137,
      "eyeLookInLeft": 0.075,
      "eyeLookInRight": 0.406,
      "eyeLookOutLeft": 0.108,
      "eyeLookOutRight": 0.003,
      "eyeLookUpLeft": 0.051,
      "eyeLookUpRight": 0.083,
      "eyeSquintLeft": 0.021,
      "eyeSquintRight": 0.021,
      "eyeWideLeft": 0.229,
      "eyeWideRight": 0.421,
      "jawForward": 0.001,
      "jawLeft": 0.001,
      "jawOpen": 0.281,
      "jawRight": 0.007,
      "mouthClose": 0.001,
      "mouthDimpleLeft": 0.005,
      "mouthDimpleRight": 0.001,
      "mouthFrownLeft": 0.001,
      "mouthFrownRight": 0.001,
      "mouthFunnel": 0.04,
      "mouthLeft": 0.001,
      "mouthLowerDownLeft": 0.437,
      "mouthLowerDownRight": 0.532,
      "mouthPressLeft": 0.009,
      "mouthPressRight": 0.007,
      "mouthPucker": 0.029,
      "mouthRight": 0,
      "mouthRollLower": 0.002,
      "mouthRollUpper": 0.012,
      "mouthShrugLower": 0,
      "mouthShrugUpper": 0.005,
      "mouthSmileLeft": 0.003,
      "mouthSmileRight": 0.003,
      "mouthStretchLeft": 0.004,
      "mouthStretchRight": 0.043,
      "mouthUpperUpLeft": 0.006,
      "mouthUpperUpRight": 0.008,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame9',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame9.jpg',
    activeKeys: ["jawOpen","mouthSmileRight","mouthSmileLeft","browOuterUpRight","browInnerUp"],
    extracted: {
      "browDownLeft": 0.006,
      "browDownRight": 0.003,
      "browInnerUp": 0.473,
      "browOuterUpLeft": 0.374,
      "browOuterUpRight": 0.497,
      "cheekPuff": 0.001,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.062,
      "eyeBlinkRight": 0.005,
      "eyeLookDownLeft": 0.084,
      "eyeLookDownRight": 0.038,
      "eyeLookInLeft": 0.364,
      "eyeLookInRight": 0.015,
      "eyeLookOutLeft": 0.011,
      "eyeLookOutRight": 0.365,
      "eyeLookUpLeft": 0.282,
      "eyeLookUpRight": 0.366,
      "eyeSquintLeft": 0.118,
      "eyeSquintRight": 0.361,
      "eyeWideLeft": 0.01,
      "eyeWideRight": 0.395,
      "jawForward": 0.001,
      "jawLeft": 0,
      "jawOpen": 0.794,
      "jawRight": 0.419,
      "mouthClose": 0,
      "mouthDimpleLeft": 0.032,
      "mouthDimpleRight": 0.019,
      "mouthFrownLeft": 0.065,
      "mouthFrownRight": 0.138,
      "mouthFunnel": 0.141,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.252,
      "mouthLowerDownRight": 0.312,
      "mouthPressLeft": 0.001,
      "mouthPressRight": 0.002,
      "mouthPucker": 0.061,
      "mouthRight": 0.007,
      "mouthRollLower": 0,
      "mouthRollUpper": 0,
      "mouthShrugLower": 0.001,
      "mouthShrugUpper": 0.112,
      "mouthSmileLeft": 0.558,
      "mouthSmileRight": 0.724,
      "mouthStretchLeft": 0.024,
      "mouthStretchRight": 0.431,
      "mouthUpperUpLeft": 0.061,
      "mouthUpperUpRight": 0.17,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame9b',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame9.jpg',
    activeKeys: ["jawOpen","mouthSmileRight","mouthSmileLeft","browOuterUpRight","browInnerUp"],
    extracted: {
      "jawOpen": 0.794,
      "mouthSmileLeft": 0.558,
      "mouthSmileRight": 0.724,
      "browOuterUpRight": 0.497,
      "browInnerUp": 0.473,
    },
    weights: {},
  },
  {
    id: 'frame1b',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame1.jpg',
    activeKeys: ["mouthLowerDownRight","mouthLowerDownLeft","browOuterUpLeft","browInnerUp","browOuterUpRight"],
    extracted: {
      "mouthLowerDownRight": 0.747,
      "mouthLowerDownLeft": 0.735,
      "browOuterUpLeft": 0.73,
      "browInnerUp": 0.641,
      "browOuterUpRight": 0.577,
    },
    weights: {},
  },
  {
    id: 'frame3',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame3.jpg',
    activeKeys: ["mouthPucker","browOuterUpLeft","browOuterUpRight","browInnerUp","eyeLookInLeft"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0,
      "browInnerUp": 0.875,
      "browOuterUpLeft": 0.934,
      "browOuterUpRight": 0.925,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.008,
      "eyeBlinkRight": 0.003,
      "eyeLookDownLeft": 0.176,
      "eyeLookDownRight": 0.143,
      "eyeLookInLeft": 0.566,
      "eyeLookInRight": 0.009,
      "eyeLookOutLeft": 0.004,
      "eyeLookOutRight": 0.532,
      "eyeLookUpLeft": 0.105,
      "eyeLookUpRight": 0.101,
      "eyeSquintLeft": 0.077,
      "eyeSquintRight": 0.043,
      "eyeWideLeft": 0.071,
      "eyeWideRight": 0.425,
      "jawForward": 0,
      "jawLeft": 0,
      "jawOpen": 0.054,
      "jawRight": 0.209,
      "mouthClose": 0.002,
      "mouthDimpleLeft": 0.022,
      "mouthDimpleRight": 0.001,
      "mouthFrownLeft": 0,
      "mouthFrownRight": 0,
      "mouthFunnel": 0.138,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.06,
      "mouthLowerDownRight": 0.19,
      "mouthPressLeft": 0.002,
      "mouthPressRight": 0.001,
      "mouthPucker": 0.966,
      "mouthRight": 0.118,
      "mouthRollLower": 0.03,
      "mouthRollUpper": 0.101,
      "mouthShrugLower": 0.001,
      "mouthShrugUpper": 0.007,
      "mouthSmileLeft": 0,
      "mouthSmileRight": 0,
      "mouthStretchLeft": 0,
      "mouthStretchRight": 0.007,
      "mouthUpperUpLeft": 0.001,
      "mouthUpperUpRight": 0,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
]);
