export type Caricature = {
  id: string;
  label: string;
  emoji: string;
  photo?: string;
  /** Full 52-blendshape map captured from the reference photo via /extract. */
  extracted?: Record<string, number>;
  /** Subset of blendshape names that count toward the match score. */
  activeKeys?: string[];
  /** Hand-tuned values that win over `extracted` for the given key. */
  overrides?: Record<string, number>;
  /** Resolved scoring target. Computed from extracted+activeKeys+overrides if absent. */
  target: Record<string, number>;
  weights?: Record<string, number>;
  threshold?: number;
  /** Soft cap per face in ms; default 20000. On expiry, advance with a miss. */
  capMs?: number;
};

type RawCaricature = Omit<Caricature, 'target'> & { target?: Record<string, number> };

function resolveTarget(c: RawCaricature): Record<string, number> {
  if (c.target) return c.target;
  if (!c.extracted || !c.activeKeys) {
    throw new Error(
      `Caricature ${c.id} needs either target or (extracted + activeKeys)`,
    );
  }
  const out: Record<string, number> = {};
  for (const k of c.activeKeys) {
    const v = c.overrides?.[k] ?? c.extracted[k];
    if (v != null) out[k] = v;
  }
  return out;
}

function resolve(list: RawCaricature[]): Caricature[] {
  return list.map((c) => ({ ...c, target: resolveTarget(c) }));
}

// Universal play order. Anchor with the intro hero (frame-4), then sequential.
// The threshold-reduced trio (1, 2, 3) lands at the end so players are warmed
// up by then.
const PLAY_ORDER = ['frame-4', 'frame-5', 'frame-6', 'frame-7', 'frame-8', 'frame-1', 'frame-2', 'frame-3'];

const RAW_CARICATURES: RawCaricature[] = ([
  {
    id: 'frame-1',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame 1.jpg',
    threshold: 0.72,
    activeKeys: ["mouthLowerDownLeft","mouthLowerDownRight","browOuterUpRight","mouthStretchLeft","eyeWideRight"],
    extracted: {
      "browDownLeft": 0.004,
      "browDownRight": 0.001,
      "browInnerUp": 0.354,
      "browOuterUpLeft": 0.2,
      "browOuterUpRight": 0.688,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.009,
      "eyeBlinkRight": 0.001,
      "eyeLookDownLeft": 0.117,
      "eyeLookDownRight": 0.056,
      "eyeLookInLeft": 0.204,
      "eyeLookInRight": 0.108,
      "eyeLookOutLeft": 0.033,
      "eyeLookOutRight": 0.075,
      "eyeLookUpLeft": 0.103,
      "eyeLookUpRight": 0.153,
      "eyeSquintLeft": 0.013,
      "eyeSquintRight": 0.018,
      "eyeWideLeft": 0.092,
      "eyeWideRight": 0.491,
      "jawForward": 0.004,
      "jawLeft": 0,
      "jawOpen": 0.067,
      "jawRight": 0.019,
      "mouthClose": 0,
      "mouthDimpleLeft": 0.016,
      "mouthDimpleRight": 0.003,
      "mouthFrownLeft": 0.008,
      "mouthFrownRight": 0.009,
      "mouthFunnel": 0.031,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.92,
      "mouthLowerDownRight": 0.911,
      "mouthPressLeft": 0.016,
      "mouthPressRight": 0.007,
      "mouthPucker": 0.007,
      "mouthRight": 0,
      "mouthRollLower": 0.003,
      "mouthRollUpper": 0.006,
      "mouthShrugLower": 0,
      "mouthShrugUpper": 0.015,
      "mouthSmileLeft": 0.15,
      "mouthSmileRight": 0.119,
      "mouthStretchLeft": 0.582,
      "mouthStretchRight": 0.234,
      "mouthUpperUpLeft": 0.137,
      "mouthUpperUpRight": 0.133,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame-2',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame 2.jpg',
    threshold: 0.72,
    activeKeys: ["browInnerUp","browOuterUpRight","browOuterUpLeft","eyeLookUpRight","mouthPucker"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0,
      "browInnerUp": 0.868,
      "browOuterUpLeft": 0.836,
      "browOuterUpRight": 0.848,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.032,
      "eyeBlinkRight": 0.006,
      "eyeLookDownLeft": 0.051,
      "eyeLookDownRight": 0.028,
      "eyeLookInLeft": 0.058,
      "eyeLookInRight": 0.122,
      "eyeLookOutLeft": 0.092,
      "eyeLookOutRight": 0.042,
      "eyeLookUpLeft": 0.257,
      "eyeLookUpRight": 0.339,
      "eyeSquintLeft": 0.177,
      "eyeSquintRight": 0.229,
      "eyeWideLeft": 0.015,
      "eyeWideRight": 0.115,
      "jawForward": 0,
      "jawLeft": 0,
      "jawOpen": 0.004,
      "jawRight": 0.012,
      "mouthClose": 0,
      "mouthDimpleLeft": 0.002,
      "mouthDimpleRight": 0.001,
      "mouthFrownLeft": 0.005,
      "mouthFrownRight": 0.006,
      "mouthFunnel": 0.01,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.003,
      "mouthLowerDownRight": 0.006,
      "mouthPressLeft": 0.022,
      "mouthPressRight": 0.007,
      "mouthPucker": 0.314,
      "mouthRight": 0.002,
      "mouthRollLower": 0.008,
      "mouthRollUpper": 0.002,
      "mouthShrugLower": 0.006,
      "mouthShrugUpper": 0.017,
      "mouthSmileLeft": 0,
      "mouthSmileRight": 0,
      "mouthStretchLeft": 0.003,
      "mouthStretchRight": 0.006,
      "mouthUpperUpLeft": 0,
      "mouthUpperUpRight": 0,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame-3',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame 3.jpg',
    threshold: 0.72,
    activeKeys: ["mouthPucker","browOuterUpLeft","browOuterUpRight","browInnerUp","eyeLookInLeft"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0,
      "browInnerUp": 0.875,
      "browOuterUpLeft": 0.934,
      "browOuterUpRight": 0.925,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.008,
      "eyeBlinkRight": 0.003,
      "eyeLookDownLeft": 0.176,
      "eyeLookDownRight": 0.143,
      "eyeLookInLeft": 0.566,
      "eyeLookInRight": 0.009,
      "eyeLookOutLeft": 0.004,
      "eyeLookOutRight": 0.532,
      "eyeLookUpLeft": 0.105,
      "eyeLookUpRight": 0.101,
      "eyeSquintLeft": 0.077,
      "eyeSquintRight": 0.043,
      "eyeWideLeft": 0.071,
      "eyeWideRight": 0.425,
      "jawForward": 0,
      "jawLeft": 0,
      "jawOpen": 0.054,
      "jawRight": 0.209,
      "mouthClose": 0.002,
      "mouthDimpleLeft": 0.022,
      "mouthDimpleRight": 0.001,
      "mouthFrownLeft": 0,
      "mouthFrownRight": 0,
      "mouthFunnel": 0.138,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.06,
      "mouthLowerDownRight": 0.19,
      "mouthPressLeft": 0.002,
      "mouthPressRight": 0.001,
      "mouthPucker": 0.966,
      "mouthRight": 0.118,
      "mouthRollLower": 0.03,
      "mouthRollUpper": 0.101,
      "mouthShrugLower": 0.001,
      "mouthShrugUpper": 0.007,
      "mouthSmileLeft": 0,
      "mouthSmileRight": 0,
      "mouthStretchLeft": 0,
      "mouthStretchRight": 0.007,
      "mouthUpperUpLeft": 0.001,
      "mouthUpperUpRight": 0,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame-4',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame 4.jpg',
    activeKeys: ["eyeSquintRight","mouthLowerDownRight","eyeLookDownRight","eyeLookDownLeft","mouthUpperUpRight"],
    extracted: {
      "browDownLeft": 0.002,
      "browDownRight": 0.001,
      "browInnerUp": 0.309,
      "browOuterUpLeft": 0.37,
      "browOuterUpRight": 0.228,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.109,
      "eyeBlinkRight": 0.1,
      "eyeLookDownLeft": 0.406,
      "eyeLookDownRight": 0.409,
      "eyeLookInLeft": 0.036,
      "eyeLookInRight": 0.196,
      "eyeLookOutLeft": 0.185,
      "eyeLookOutRight": 0.017,
      "eyeLookUpLeft": 0.034,
      "eyeLookUpRight": 0.032,
      "eyeSquintLeft": 0.385,
      "eyeSquintRight": 0.555,
      "eyeWideLeft": 0.012,
      "eyeWideRight": 0.014,
      "jawForward": 0.001,
      "jawLeft": 0.012,
      "jawOpen": 0.205,
      "jawRight": 0,
      "mouthClose": 0.001,
      "mouthDimpleLeft": 0.013,
      "mouthDimpleRight": 0.022,
      "mouthFrownLeft": 0,
      "mouthFrownRight": 0,
      "mouthFunnel": 0.135,
      "mouthLeft": 0.001,
      "mouthLowerDownLeft": 0.371,
      "mouthLowerDownRight": 0.43,
      "mouthPressLeft": 0.005,
      "mouthPressRight": 0.019,
      "mouthPucker": 0.026,
      "mouthRight": 0,
      "mouthRollLower": 0.004,
      "mouthRollUpper": 0.002,
      "mouthShrugLower": 0.001,
      "mouthShrugUpper": 0.029,
      "mouthSmileLeft": 0.02,
      "mouthSmileRight": 0.021,
      "mouthStretchLeft": 0.002,
      "mouthStretchRight": 0.002,
      "mouthUpperUpLeft": 0.361,
      "mouthUpperUpRight": 0.4,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame-5',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame 5.jpg',
    activeKeys: ["browInnerUp","browOuterUpLeft","browOuterUpRight","mouthLowerDownRight","mouthLowerDownLeft"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0,
      "browInnerUp": 0.798,
      "browOuterUpLeft": 0.773,
      "browOuterUpRight": 0.739,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.003,
      "eyeBlinkRight": 0.001,
      "eyeLookDownLeft": 0.247,
      "eyeLookDownRight": 0.137,
      "eyeLookInLeft": 0.075,
      "eyeLookInRight": 0.406,
      "eyeLookOutLeft": 0.108,
      "eyeLookOutRight": 0.003,
      "eyeLookUpLeft": 0.051,
      "eyeLookUpRight": 0.083,
      "eyeSquintLeft": 0.021,
      "eyeSquintRight": 0.021,
      "eyeWideLeft": 0.229,
      "eyeWideRight": 0.421,
      "jawForward": 0.001,
      "jawLeft": 0.001,
      "jawOpen": 0.281,
      "jawRight": 0.007,
      "mouthClose": 0.001,
      "mouthDimpleLeft": 0.005,
      "mouthDimpleRight": 0.001,
      "mouthFrownLeft": 0.001,
      "mouthFrownRight": 0.001,
      "mouthFunnel": 0.04,
      "mouthLeft": 0.001,
      "mouthLowerDownLeft": 0.437,
      "mouthLowerDownRight": 0.532,
      "mouthPressLeft": 0.009,
      "mouthPressRight": 0.007,
      "mouthPucker": 0.029,
      "mouthRight": 0,
      "mouthRollLower": 0.002,
      "mouthRollUpper": 0.012,
      "mouthShrugLower": 0,
      "mouthShrugUpper": 0.005,
      "mouthSmileLeft": 0.003,
      "mouthSmileRight": 0.003,
      "mouthStretchLeft": 0.004,
      "mouthStretchRight": 0.043,
      "mouthUpperUpLeft": 0.006,
      "mouthUpperUpRight": 0.008,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame-6',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame 6.jpg',
    activeKeys: ["mouthLowerDownRight","mouthLowerDownLeft","browOuterUpLeft","browInnerUp","browOuterUpRight"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0,
      "browInnerUp": 0.641,
      "browOuterUpLeft": 0.73,
      "browOuterUpRight": 0.577,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.022,
      "eyeBlinkRight": 0.013,
      "eyeLookDownLeft": 0.047,
      "eyeLookDownRight": 0.048,
      "eyeLookInLeft": 0.164,
      "eyeLookInRight": 0.066,
      "eyeLookOutLeft": 0.025,
      "eyeLookOutRight": 0.074,
      "eyeLookUpLeft": 0.283,
      "eyeLookUpRight": 0.254,
      "eyeSquintLeft": 0.392,
      "eyeSquintRight": 0.252,
      "eyeWideLeft": 0.056,
      "eyeWideRight": 0.069,
      "jawForward": 0.001,
      "jawLeft": 0,
      "jawOpen": 0.568,
      "jawRight": 0.244,
      "mouthClose": 0.002,
      "mouthDimpleLeft": 0.066,
      "mouthDimpleRight": 0.075,
      "mouthFrownLeft": 0.001,
      "mouthFrownRight": 0.001,
      "mouthFunnel": 0.009,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.735,
      "mouthLowerDownRight": 0.747,
      "mouthPressLeft": 0.005,
      "mouthPressRight": 0.011,
      "mouthPucker": 0.043,
      "mouthRight": 0.007,
      "mouthRollLower": 0.004,
      "mouthRollUpper": 0.018,
      "mouthShrugLower": 0.001,
      "mouthShrugUpper": 0.004,
      "mouthSmileLeft": 0,
      "mouthSmileRight": 0.001,
      "mouthStretchLeft": 0,
      "mouthStretchRight": 0.005,
      "mouthUpperUpLeft": 0.002,
      "mouthUpperUpRight": 0.001,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame-7',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame 7.jpg',
    activeKeys: ["mouthLowerDownLeft","browInnerUp","browOuterUpRight","browOuterUpLeft","mouthLowerDownRight"],
    extracted: {
      "browDownLeft": 0,
      "browDownRight": 0,
      "browInnerUp": 0.799,
      "browOuterUpLeft": 0.79,
      "browOuterUpRight": 0.796,
      "cheekPuff": 0,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.004,
      "eyeBlinkRight": 0.001,
      "eyeLookDownLeft": 0.183,
      "eyeLookDownRight": 0.163,
      "eyeLookInLeft": 0.05,
      "eyeLookInRight": 0.154,
      "eyeLookOutLeft": 0.119,
      "eyeLookOutRight": 0.019,
      "eyeLookUpLeft": 0.069,
      "eyeLookUpRight": 0.082,
      "eyeSquintLeft": 0.028,
      "eyeSquintRight": 0.017,
      "eyeWideLeft": 0.185,
      "eyeWideRight": 0.489,
      "jawForward": 0.002,
      "jawLeft": 0.023,
      "jawOpen": 0.317,
      "jawRight": 0,
      "mouthClose": 0.001,
      "mouthDimpleLeft": 0.003,
      "mouthDimpleRight": 0.01,
      "mouthFrownLeft": 0.009,
      "mouthFrownRight": 0.009,
      "mouthFunnel": 0.015,
      "mouthLeft": 0,
      "mouthLowerDownLeft": 0.845,
      "mouthLowerDownRight": 0.614,
      "mouthPressLeft": 0.006,
      "mouthPressRight": 0.017,
      "mouthPucker": 0.008,
      "mouthRight": 0,
      "mouthRollLower": 0.002,
      "mouthRollUpper": 0.007,
      "mouthShrugLower": 0,
      "mouthShrugUpper": 0.01,
      "mouthSmileLeft": 0.014,
      "mouthSmileRight": 0.018,
      "mouthStretchLeft": 0.051,
      "mouthStretchRight": 0.03,
      "mouthUpperUpLeft": 0.021,
      "mouthUpperUpRight": 0.048,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
  {
    id: 'frame-8',
    label: 'Label here',
    emoji: '😐',
    photo: '/faces/Frame 8.jpg',
    activeKeys: ["mouthUpperUpRight","mouthLowerDownLeft","mouthLowerDownRight","mouthUpperUpLeft","browOuterUpRight"],
    extracted: {
      "browDownLeft": 0.025,
      "browDownRight": 0.037,
      "browInnerUp": 0.107,
      "browOuterUpLeft": 0.343,
      "browOuterUpRight": 0.603,
      "cheekPuff": 0.001,
      "cheekSquintLeft": 0,
      "cheekSquintRight": 0,
      "eyeBlinkLeft": 0.083,
      "eyeBlinkRight": 0.116,
      "eyeLookDownLeft": 0.323,
      "eyeLookDownRight": 0.529,
      "eyeLookInLeft": 0.049,
      "eyeLookInRight": 0.266,
      "eyeLookOutLeft": 0.135,
      "eyeLookOutRight": 0.005,
      "eyeLookUpLeft": 0.046,
      "eyeLookUpRight": 0.015,
      "eyeSquintLeft": 0.078,
      "eyeSquintRight": 0.077,
      "eyeWideLeft": 0.088,
      "eyeWideRight": 0.021,
      "jawForward": 0.001,
      "jawLeft": 0.002,
      "jawOpen": 0.032,
      "jawRight": 0.002,
      "mouthClose": 0,
      "mouthDimpleLeft": 0.012,
      "mouthDimpleRight": 0.01,
      "mouthFrownLeft": 0.406,
      "mouthFrownRight": 0.421,
      "mouthFunnel": 0.24,
      "mouthLeft": 0.001,
      "mouthLowerDownLeft": 0.832,
      "mouthLowerDownRight": 0.817,
      "mouthPressLeft": 0.028,
      "mouthPressRight": 0.029,
      "mouthPucker": 0.023,
      "mouthRight": 0,
      "mouthRollLower": 0.027,
      "mouthRollUpper": 0.001,
      "mouthShrugLower": 0.02,
      "mouthShrugUpper": 0.293,
      "mouthSmileLeft": 0.416,
      "mouthSmileRight": 0.519,
      "mouthStretchLeft": 0.019,
      "mouthStretchRight": 0.024,
      "mouthUpperUpLeft": 0.806,
      "mouthUpperUpRight": 0.843,
      "noseSneerLeft": 0,
      "noseSneerRight": 0
    },
    weights: {},
  },
]);

const RAW_BY_ID = new Map(RAW_CARICATURES.map((c) => [c.id, c]));
const ORDERED_RAW = PLAY_ORDER.map((id) => {
  const c = RAW_BY_ID.get(id);
  if (!c) throw new Error(`PLAY_ORDER references unknown id: ${id}`);
  return c;
});

export const PLACEHOLDER_CARICATURES: Caricature[] = resolve(ORDERED_RAW);
